# config.yml

LOG_DIR: data_log
LOG_PREFIX_DIR: data_prefix
LOG_ENCODING_DIR: data_encoding
STATS_DIR: stats
ML_DIR: data_ml
PLOT_DIR: plots
SHAP_DIR: shap

# Event log main columns
CASEID_COL: CaseID
ACTIVITY_COL: ACTIVITY
TIMESTAMP_COL: TIMESTAMP

# Distinction between standard and enriched event logs
STD_SUFFIX: std
ENR_SUFFIX: enr

# Event log feature types
EVENT_LOG_TYPES:
  CaseID: object
  ACTIVITY: object
  TIMESTAMP: object
  RESOURCE: object
  ESI: int
  OUTCOME: object
  INPAT-HOSP-DEP: object
  CASE_DURATION_sec: float
  REMAINING_TIME_sec: float
  Active_CaseID: int
  TIMESTAMP_HH: int
  COUNT-ESI-1: int
  COUNT-ESI-2: int
  COUNT-ESI-3: int
  COUNT-ESI-4: int
  COUNT-ESI-5: int
  CLUSTER: int

# Cross Validation
CV_FOLDS: 5

HOSPITAL_TERMS:
  TRIAGE: "TRIAGE"
  DIMISSIONE: "DISCHARGE"
  PRESA IN CARICO: "PHYSICIAN-ASSESMENT"
  LABORATORIO: "LABORATORY"
  RX: "X-RAY"
  ELETTROCARDIOGRAMMA: "EKG"
  CONSULENZA: "CONSULTATION"
  RX THORAX / TH+LAT: "CHEST X-RAY / THORAX+LATERAL"
  TAC: "CT SCAN"
  TC CRANIO: "BRAIN CT SCAN"
  CONTROLLI PRETRASF.: "PRE-TRANSFUSIONAL CHECKS"
  OBI: "OBSERVATION UNIT"
  RX THORAX BED: "BED CHEST X-RAY"
  ECOGRAF.RENOVESCICALE: "RENAL ULTRASOUND"
  ECOGRAFIA ADDOME SUP.: "UPPER ABDOMINAL ULTRASOUND"
  ECOGRAF.ADDOME COMPLETO: "COMPLETE ABDOMINAL ULTRASOUND"
  ELETTROENCEFALOGRAMMA: "EEG"
  RM: "MRI"
  ESOFAGOGASTRODUODENOSCOPIA [EGD]: "ESOPHAGOGASTRODUODENOSCOPY [EGD]"
  ECOGRAFIA ADDOME INFERIORE: "LOWER ABDOMINAL ULTRASOUND"
  BRONCOSCOPIA CON FIBRE OTTICHE: "FIBEROPTIC BRONCHOSCOPY"
  ECOGRAFIA SCROTALE/TESTICOLARE: "SCROTAL/TESTICULAR ULTRASOUND"
  ECO-DOPPLER TRONCHI SOVRAORTICI: "CAROTID DOPPLER ULTRASOUND"
  ARCATA DENTARIA COMPLETA (SUP O INF): "COMPLETE DENTAL ARCH (UPPER OR LOWER)"
  TERAPIA INFUSIONALE: "INTRAVENOUS THERAPY"
  ECOGRAFIA MUSCOLO TENDINEA: "MUSCLE TENDON ULTRASOUND"
  STESURA PIANO DIALITICO: "DIALYSIS PLAN DEVELOPMENT"
  MEDICAZIONE NEFROLOGICA: "NEPHROLOGICAL TREATMENT"
  CONTROLLO NEFROLOGICO: "NEPHROLOGICAL CONSULTATION"
  BICARBONATO DIALISI: "DIALYSIS"
  PRELIEVO VENOSO: "VENOUS SAMPLING"
  ECO-DOPPLER VENOSO ARTI INF.: "VENOUS DOPPLER ULTRASOUND OF LOWER LIMBS"
  PRELIEVO CITOLOGICO: "CYTOLOGICAL SAMPLING"
  NARCOSI: "NARCOSIS"
  IRRIGAZIONE CATETERE VENOSO: "VENOUS CATHETER FLUSHING"
  CONTROLLO PM-ICD-LOOP: "PACEMAKER-ICD-LOOP CHECK"
  EGA VENOSO: "VENOUS BLOOD GAS ANALYSIS"
  EMODIAFILTRAZIONE: "HAEMODIAFILTRATION"
  COLONSCOPIA CON ENDOSCOPIO FLESSIBILE: "COLONOSCOPY WITH FLEXIBLE ENDOSCOPE"
  INTERVENTI ENDOSCOPICI IN TRACHEA: "ENDOSCOPIC PROCEDURES IN TRACHEA"
  FASCIATURA SEMPLICE: "SIMPLE BANDAGE"
  BIOPSIA/CITOLOGIA BRONCHIALE: "BRONCHIAL BIOPSY/CYTOLOGY"
  BRONCOSCOPIA RIGIDA: "RIGID BRONCHOSCOPY"
  TEST DA SFORZO: "STRESS TEST"
  VALUTAZIONE MULTIDISCIPLINARE: "MULTIDISCIPLINARY EVALUATION"
  ALTRI INTERVENTI SULLA TRACHEA: "OTHER TRACHEAL PROCEDURES"
  ASPORTAZIONE O DEMOLIZIONE ENDOSCOPICA DI LESIONE O TESSUTO NEI BRONCHI: "ENDOSCOPIC REMOVAL OR ABLATION OF LESION OR TISSUE IN BRONCHI"
  ALTRA INTUBAZIONE DEL TRATTO RESPIRATORIO (INSERZIONE STENT): "OTHER RESPIRATORY TRACT INTUBATION (STENT PLACEMENT)"
  RIMOZIONE ENDOSCOPICA DI DISPOSITIVO E SOSTANZE BRONCHIALI: "ENDOSCOPIC REMOVAL OF DEVICE AND BRONCHIAL SUBSTANCES"
  INTERVENTI SUL BRONCO CON POSIZIONAMENTO DI STENT/ARGON NEI BRONCHI: "BRONCHIAL PROCEDURES WITH STENT/ARGON PLACEMENT IN BRONCHI"
  ECOGRAFIA CUTE E TESSUTO: "SKIN AND TISSUE ULTRASOUND"
  TEST CARDIOVASCOLARE DA SFORZO CON CICLOERGOMETRO: "CARDIOVASCULAR STRESS TEST"
  INIEZIONE EPO: "EPO INJECTION"
  BIOPSIA LINFONODO: "LYMPH NODE BIOPSY"
  LARINGOSCOPIA: "LARYNGOSCOPY"
  ECG: "EKG"
  POSIZIONAMENTO DI CATETERE VENOSO CENTRALE (CVC): "CENTRAL VENOUS CATHETER (CVC) PLACEMENT"
  ECO-DOPPLER ARTERIOSO ARTI INF.: "ARTERIAL DOPPLER ULTRASOUND OF LOWER LIMBS"
  PRELIEVO MICROBIOLOGICO: "MICROBIOLOGICAL SAMPLING"
  ECOGRAFIA PENIENA: "PENILE ULTRASOUND"
